captcha:

  enabled: true

  enabled-worlds:
    - world

  disabled-worlds:
    - spawn

  min-blocks: 30
  max-blocks: 80

  success-cooldown: 120

  freeze-player: true

  block-commands: true

  timeout-seconds: 10

  allowed-commands:
    - msg
    - r

  ignored-blocks:
    - TORCH
    - GRASS
    - TALL_GRASS

  gui:

    size: 27

    title: "&cKlikni na BEDROCK"

    fill-material: STONE

    captcha-material: BEDROCK

messages:

  success: "&aÚspěšně ověřeno!"

  fail: "&cNeprošel jsi CAPTCHA testem!"

  close: "&cZavřel jsi CAPTCHA!"

  timeout: "&cVypršel čas na CAPTCHA!"

  blocked-commands: "&cBěhem CAPTCHA nemůžeš používat commandy!"

  already-open: "&cUž řešíš CAPTCHA!"

  reload: "&aConfig byl reloadnut!"
