name: XCaptcha

version: 1.0

main: me.xverse.captcha.Main

api-version: '1.21'

author: MrXlson

commands:
  xcaptcha:
    permission: xcaptcha.admin

permissions:

  xcaptcha.admin:
    default: op

  xcaptcha.bypass:
    default: op
